"use client";

// The <img> every product picture on the site renders through.
//
// WHAT IT CHANGES, AND WHY IT IS NOT JUST A WRAPPER
//
// 1. It never sends `src` straight to the browser. It asks lib/image-url.ts for
//    a srcset of real, differently-sized WebP files, so a 40px design chip
//    downloads a 400px file instead of the 1080px original, and a retina screen
//    still gets a crisp 800px file instead of a blurry upscaled 400px one.
//
// 2. It cannot leave a page full of broken pictures. The derivatives are
//    generated by a one-off script, so until that script has covered a given
//    URL the candidate may not exist yet. When the browser reports the failure
//    this component falls back to the original file and remembers the URL, so
//    the rest of the session stops asking for a file that is not there.
//
// 3. It owns `loading`/`fetchPriority` defaults, which is how the "70 eager
//    high-priority images" problem gets fixed at the source: a picture is only
//    eager+high when its caller says that picture is the one the customer is
//    looking at right now. Everything else defaults to lazy.
//
// It renders ONE <img>. It deliberately does not own opacity, crossfades or
// stacking - the gallery needs to drive those itself as the customer moves
// between pictures, and a second opinion there would fight the parent's classes.

import { useCallback, useEffect, useState, type CSSProperties } from "react";
import {
  imageSrcSet,
  imageUrl,
  noteMissingDerivative,
  derivativeWidthFromUrl,
  availableWidths,
  hasDerivatives,
} from "@/lib/image-url";

export interface SmartImageProps {
  /** The stored original URL (a Supabase Storage object for product photos). */
  src: string;
  /**
   * The real on-screen width of this slot in CSS px. Used only to choose the
   * `src` fallback; the browser itself uses `sizes` for the actual picking.
   */
  cssWidth: number;
  /** A `sizes` value from lib/image-url.ts IMAGE_SIZES. */
  sizes: string;
  /** Meaningful alt text. Pass "" for a decorative picture. */
  alt: string;
  className?: string;
  style?: CSSProperties;
  loading?: "lazy" | "eager";
  fetchPriority?: "high" | "low" | "auto";
  draggable?: boolean;
  /** For a picture that is stacked behind the visible one but still a real <img>. */
  "aria-hidden"?: boolean;
  /** Fired once the browser has the picture decoded (or has given up on it). */
  onLoad?: () => void;
}

export function SmartImage({
  src,
  cssWidth,
  sizes,
  alt,
  className,
  style,
  loading = "lazy",
  fetchPriority = "auto",
  draggable,
  "aria-hidden": ariaHidden,
  onLoad,
}: SmartImageProps) {
  // Set when this picture's every remaining candidate turned out to be missing:
  // from then on this component asks for the original and nothing else.
  const [useOriginal, setUseOriginal] = useState(false);

  // Bumped whenever a tier is dropped as missing, because recording that in the
  // shared table does not re-render this component by itself and the srcset below
  // would keep advertising a file the browser has already proven is not there.
  // The value is never read - the state change is the whole point.
  const [, setRevision] = useState(0);

  // A picture that changes URL (switching design, cycling the carousel) must
  // start trusting derivatives again for the new URL.
  useEffect(() => {
    setUseOriginal(false);
  }, [src]);

  const srcSet = useOriginal ? "" : imageSrcSet(src);
  const resolved = useOriginal ? src : imageUrl(src, cssWidth);

  const handleError = useCallback(
    (event: React.SyntheticEvent<HTMLImageElement>) => {
      // Nothing to fall back to for a non-Storage picture (placeholder, external
      // host): the browser's own broken-image state is the honest answer.
      if (!hasDerivatives(src)) return;

      // Work out WHICH tier failed rather than condemning the whole picture.
      // `currentSrc` is the exact file the browser chose, so a missing 800px no
      // longer drags a perfectly good 400px down with it.
      const failedWidth = derivativeWidthFromUrl(src, event.currentTarget.currentSrc);

      // `currentSrc` can be empty while the element is still resolving, and a
      // candidate can be missing for a reason no tier can explain. Dropping every
      // width is the old all-or-nothing behaviour and stays the right last resort.
      noteMissingDerivative(src, failedWidth ?? undefined);

      if (availableWidths(src).length === 0) {
        setUseOriginal(true);
        return;
      }

      // Still something smaller than the original: rebuild the srcset without the
      // tier that just failed and let the browser pick again.
      setRevision((r) => r + 1);
    },
    [src],
  );

  return (
    <img
      src={resolved}
      srcSet={srcSet || undefined}
      sizes={srcSet ? sizes : undefined}
      alt={alt}
      className={className}
      style={style}
      aria-hidden={ariaHidden}
      loading={loading}
      fetchPriority={fetchPriority}
      decoding="async"
      draggable={draggable ?? false}
      onLoad={onLoad}
      onError={handleError}
    />
  );
}
