export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  images?: string[];
  inStock: boolean;
  rating: number;
  reviews: number;
}

export const products: Product[] = [
  // Anime Keychains
  {
    id: 'neon-genesis',
    name: 'Neon Genesis Evangelion',
    description: 'Classic mecha anime keychain with iconic EVA Unit design',
    price: 599,
    category: 'Anime',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.8,
    reviews: 342,
  },
  {
    id: 'attack-titan',
    name: 'Attack on Titan',
    description: 'Dynamic action keychain featuring the Scout Regiment emblem',
    price: 549,
    category: 'Anime',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.9,
    reviews: 567,
  },
  {
    id: 'demon-slayer',
    name: 'Demon Slayer',
    description: 'Beautiful Demon Slayer Corps insignia keychain with sword charm',
    price: 649,
    category: 'Anime',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.7,
    reviews: 421,
  },
  {
    id: 'jujutsu-kaisen',
    name: 'Jujutsu Kaisen',
    description: 'Sorcery-themed keychain with Jujutsu High emblem',
    price: 599,
    category: 'Anime',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.8,
    reviews: 389,
  },
  {
    id: 'my-hero',
    name: 'My Hero Academia',
    description: 'Heroes and villains collection keychain from the hit series',
    price: 499,
    category: 'Anime',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.6,
    reviews: 298,
  },
  {
    id: 'steins-gate',
    name: "Steins;Gate",
    description: 'Time travel sci-fi keychain with iconic lab emblem',
    price: 549,
    category: 'Anime',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.9,
    reviews: 245,
  },
  // Superhero Keychains
  {
    id: 'batman',
    name: 'Batman Icon',
    description: 'Dark Knight Batman emblem keychain with premium finish',
    price: 599,
    category: 'Superhero',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.8,
    reviews: 312,
  },
  {
    id: 'superman',
    name: 'Superman Shield',
    description: 'Iconic Superman S shield keychain with vibrant colors',
    price: 599,
    category: 'Superhero',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.7,
    reviews: 287,
  },
  {
    id: 'wonder-woman',
    name: 'Wonder Woman Lasso',
    description: 'Wonder Woman inspired keychain with golden accents',
    price: 649,
    category: 'Superhero',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.9,
    reviews: 198,
  },
  // Marvel Keychains
  {
    id: 'iron-man',
    name: 'Iron Man Arc Reactor',
    description: 'Glowing Iron Man arc reactor keychain replica',
    price: 699,
    category: 'Marvel',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.9,
    reviews: 456,
  },
  {
    id: 'spider-man',
    name: 'Spider-Man Web',
    description: 'Spider-Man web design keychain with red and blue finish',
    price: 549,
    category: 'Marvel',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.8,
    reviews: 387,
  },
  {
    id: 'thor-hammer',
    name: 'Thor Mjolnir',
    description: 'Mighty Mjolnir hammer keychain with detailed sculpting',
    price: 749,
    category: 'Marvel',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.9,
    reviews: 523,
  },
  // DC Keychains
  {
    id: 'flash',
    name: 'The Flash Lightning',
    description: 'The Flash lightning bolt keychain with metallic finish',
    price: 549,
    category: 'DC',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.7,
    reviews: 264,
  },
  {
    id: 'aquaman',
    name: 'Aquaman Trident',
    description: 'Aquaman trident keychain with ocean blue accents',
    price: 599,
    category: 'DC',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.6,
    reviews: 156,
  },
  // Sports Keychains
  {
    id: 'ronaldo-7',
    name: 'Cristiano Ronaldo CR7',
    description: 'Cristiano Ronaldo CR7 football legend keychain',
    price: 499,
    category: 'Sports',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.8,
    reviews: 612,
  },
  {
    id: 'messi-10',
    name: 'Lionel Messi 10',
    description: 'Lionel Messi football icon keychain with premium quality',
    price: 499,
    category: 'Sports',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.9,
    reviews: 598,
  },
  {
    id: 'football-trophy',
    name: 'Football Trophy',
    description: 'Golden football trophy keychain for sports enthusiasts',
    price: 449,
    category: 'Sports',
    image: '/placeholder-product.png',
    inStock: true,
    rating: 4.5,
    reviews: 178,
  },
];

export const categories = [
  'All',
  'Anime',
  'Superhero',
  'Marvel',
  'DC',
  'Sports',
];
